// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpczslctbfjixiumsjdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwY3pzbGN0YmZqaXhpdW1zamRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDU0MTAsImV4cCI6MjA2OTU4MTQxMH0.cFTF914AbUZ1yUdT_ew1NeSXCCvWunW0QNsYU8oY-ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});